### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-er-diagram-generator.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "beyondcode/laravel-er-diagram-generator": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by lloricode** [comment]
tested working as expected :100:

**Review by MarioAda — APPROVED** [review]

**Review by lloricode — APPROVED** [review]

**Comment by akulmehta** [comment]
This works

**Comment by dj6082013** [comment]
Is this repository still being maintained? Composer is blocking me to install this package because my PHP version is 8.

This PR seems to solve my problem. If it works, why not merge it?

**Review by gnovaro — APPROVED** [review]
Looks great

**Comment by aejnsn** [comment]
@mpociot @sschlein Can we make this happen so I don't have to fork it? Let me know if any additional changes need be made to help this along. :)

**Comment by aejnsn** [comment]
@mpociot @sschlein This is a really nice tool, but it's languishing because of dependency versions. Can we please get some eyes on this PR?

The other alternative is to sideload the Laravel Shift repository as detailed here: https://github.com/beyondcode/laravel-er-diagram-generator/pull/101#issuecomment-1030634003

If this is abandonware, let's offload responsibility to someone who will maintain it--1700 stars at the time of this writing, and we're not maintaining simple dependency details. :(

**Comment by akulmehta** [comment]
Thanks for finally merging :)

**Comment by aejnsn** [comment]
@mechelon Thank you! 💯

**Pull request merged**
