### PR TITLE
Adds tests for traits and default filenames

### PR DESCRIPTION
**Pull request by jhoff**
Just adds a few tests to cover #23 and reading traits properly.

### CODE REVIEW

**Comment by mpociot** [comment]
Please use the text output format. This way the snapshot contains the dot content of the graph, allowing you to validate that it works as intended

**Comment by jhoff** [comment]
Really all that needed to be done was to verify that the output filename is graph.jpeg so I changed to an assertion instead of using the snapshot.

**Comment by jhoff** [comment]
I don't know why this is failing on Travis. The tests pass locally for me.

**Comment by mpociot** [comment]
It's failing on travis, because on the travis containers, there graphviz is not installed. We will need to adjust the `.travis.yml` file so that it installs graphviz

**Comment by jhoff** [comment]
There we go. Looks like that worked. 👍

**Pull request merged**
